GET http://localhost:5000/api/v1/todos/init
###
GET http://localhost:5000/api/v1/todos/
###
POST http://localhost:5000/api/v1/todos/add_t/2
###
POST http://localhost:5000/api/v1/todos/add_p
###
PUT  http://localhost:5000/api/v1/todos/7
###
DELETE http://localhost:5000/api/v1/todos/4